plugins {
	id 'multiloader-loader'
	id 'net.fabricmc.fabric-loom'
}

dependencies {
	minecraft("com.mojang:minecraft:${minecraft_version}")
	implementation("net.fabricmc:fabric-loader:${fabric_loader_version}")
	implementation("net.fabricmc.fabric-api:fabric-api:${fabric_version}")
}

loom {
	runs {
		client {
			client()
			setConfigName('Fabric Client')
			ideConfigGenerated(true)
			runDir('runs/client')
		}
		server {
			server()
			setConfigName('Fabric Server')
			ideConfigGenerated(true)
			runDir('runs/server')
		}
		gametest {
			inherit server
			name "Game Test"
			vmArg "-Dfabric-api.gametest"
			vmArg "-Dfabric-api.gametest.report-file=${project.layout.buildDirectory.get().asFile}/junit.xml"
			runDir "runs/gametest"
		}
	}
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
	configurations.named(variant) {
		attributes {
			attribute(loaderAttribute, 'fabric')
		}
	}
}
sourceSets.configureEach {
	[it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
		configurations.named(variant) {
			attributes {
				attribute(loaderAttribute, 'fabric')
			}
		}
	}
}
