org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Project
version=0.3.6
group=media.jlt.minecraft.mods
java_version=25

# Common
minecraft_version=26.2
minecraft_version_range=[26.2, 26.3)
mod_id=jlt_worldz
mod_name=JLT Worldz
mod_author=Jason Taylor
license=MIT
credits=
description=Limit new worlds to a chosen set of biomes, with an optional starter biome around world spawn.

# Fabric, see https://fabricmc.net/develop/ for new versions
loom_version=1.17-SNAPSHOT
fabric_version=0.154.2+26.2
fabric_loader_version=0.19.3

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.2.0.12-beta
neoforge_loader_version_range=[4,)
neo_form_version=26.2-1

# Configuration
snakeyaml_version=2.6
